@echo off
echo Testando o projeto EmpowerUp...
cd /d "c:\xampp\htdocs\empowerup"
echo.
echo Instalando dependências faltantes...
npm install @radix-ui/react-select @radix-ui/react-dialog @radix-ui/react-dropdown-menu @radix-ui/react-avatar @radix-ui/react-tabs @radix-ui/react-checkbox @radix-ui/react-label
echo.
echo Corrigindo vulnerabilidades...
npm audit fix
echo.
echo Iniciando o projeto...
npm start
